### ISSUE TITLE
error if updated to version 1.22.1.0 

### ISSUE THREAD

**Issue by matata86** [tsujamin/hass-addons#34]
Hi, I have error if updated to version 1.22.1.0 on Home assistant...

`Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 18:54:44 (1 occurrences)
Last logged: 18:54:44

Failed to to call /store/addons/948e3081_tailscale/update - The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps' returned a non-zero code: 100`

**Comment by tsujamin** [comment]
Hey mate - can you have another try at the update? Just worked on my box so maybe you had a temporary outage to the debian repos when those packages are installed into the container

**Comment by matata86** [comment]
Still same problem. this error has been going on for several days.

**Comment by matata86** [comment]
I have second instance of HA in my office. There is update ok...

Only in my home instance is error.
The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps' returned a non-zero code: 100

But other addon in my home instance are updated succesfuly.

Any idea please?

**Comment by tsujamin** [comment]
The fact it works in the office but not at home makes me think its an issue connecting to the Debian package repos from your home... Could be a DNS or TLS issue on your home connection perhaps? Unfortunately there's not much I can do to help sorry. 

You could try using the other Home Assistant Tailscale addon from the main community store. It looks like it uses pre-built container images, so if your issue is specifically debian repo connectivity it might work for you.

**Comment by matata86** [comment]
It's weird that I use your addon several months. All was ok. Now is problem. :-/ Second addon Tailscale make some problems. Your addon works great. It just can't be updated right now.

**Comment by tsujamin** [comment]
Yeah sorry mate, I'll leave this open and try remember to bump it next minor version release incase that fixes it

**Comment by tsujamin** [comment]
just bumped to v1.22.2 incase building a new image clears up any of your issues

**Comment by matata86** [comment]
YES! Update successfuly! Thank you so much.

**Comment by tsujamin** [comment]
yesssssssss so glad to hear.

fwiw I have a theory: that your closest debian repo was out-of-sync or otherwise unreachable when you first build 1.22..1.0 and that docker cached that error until you had to build an entirely new image version.

I guess if it happens again just wait until the next version bump (I usually get them within a few days at the moment)
