### ISSUE TITLE
Add support for the --snat-subnet-routes flag

### ISSUE THREAD

**Issue by jordiorlando** [tsujamin/hass-addons#53]
**Is your feature request related to a problem? Please describe.**
In order to get [site-to-site networking](https://tailscale.com/kb/1214/site-to-site/) to work, Tailscale needs to be started with the --snat-subnet-routes flag.

**Describe the solution you'd like**
Add a toggle for the snat-subnet-routes flag to the addon’s configuration page.

**Describe alternatives you've considered**
Have tried the official Tailscale addon and it doesn’t seem to work.

**Additional context**
None.

**Comment by Gyosa3** [comment]
Hi I was looking at your pull request and I'm a bit puzzled, not sure what are the problems you're facing, and I can't say if it would solve my own problem:

I am running this add-on on my HAOS system on Raspberry Pi. I wanted to access other devices on a different vlan next to the Pi and I managed to make it work by both advertising the route of the extra vlan AND activating the "userspace_networking" flag, because otherwise it seems the traffic cannot exit the container where this addon is running.

Having made it work, I have added a second addon running AdGuard, which acts as a DNS proxy and I have setup the tailscale IP address of the Pi as DNS in the Tailscale console. It works :) when Tailscale is active on my mobile, the DNS queries are directed to the PI through the Tailscale network, sent back to the device, which then access the target IP directly. But I have 2 minor problems that I was wondering if this snat-subnet-routes flag could help solving (but it's above my technical understanding):

- problem 1: for each DNS request that hit AdGuard from the tailscale network, I have 2 entries, as if there was a bounce between the two addons. One query is issued from the IP address of the Host, e.g. 192.168.1.5, the other (same query, same timestamp) is issued from 127.0.0.1. This is not the case when a machine hits AdGuard from the local network (so from outside Tailscale). I can't figure out why there is this rebound, and if snat could play a role in there (making AdGuard understand who is the real requester maybe?)

- problem 2: all DNS requests from clients passing through Tailscale hit AdGuard with the same IP address of the Pi host. I would have expected to see the tailscale IP of the client instead. That's where I think the snat flag may be involved to uncover the originating IP that hits the addon?

If anyone has a clue what's happening here... and if the snat flag could help maybe... Thanks a lot !!

**Comment by Gyosa3** [comment]
Update on my above message: 

I have activated the "disable DNS" option in the add-on and now I seem to have gotten rid of the bouncing effect. Everything now comes from 127.0.0.1 when the DNS traffic comes from a device on the Tailscale network, while local clients show up with their local IP address. That seems to fix problem 1.

![image](https://user-images.githubusercontent.com/51777889/223070735-f3ef50ae-d3f2-462d-a1f0-743f7624f241.png)

I now am waiting for the pull request to be integrated to the add-on to activate the snat flag in the hope that it will reveal the source IP address to AdGuard...

Any date for it? Thanks

**Comment by tsujamin** [comment]
I've just merged in a change to 1.36.2.3 that adds this flag, your mileage may vary though so let me know how it goes :)
