### ISSUE TITLE
Question - Post-Up iptables addition capability

### ISSUE THREAD

**Issue by minix1234** [tsujamin/hass-addons#7]
evening,

thanks you for this cool project.  I have been playing around with tailscale and so far it works as expected.  However, I have my own security concerns and wanted to pick your brain.

As a solo plan Tailscales ACLs do not appear to be entirely active.  I can define and limit which tailscale clients can see my hassio box, but when connected traffic is wide open on any port.

To circumvent this I have added some top level iptable filters.  These do not persist after a host reboot.  Is there anyway you can think of that one might be able to execute such iptable checks/additions when this add-on starts/restarts?

**Comment by minix1234** [comment]
For example, Tailscale adds a reference in the INPUT chain to the `ts-input` chain.  This holds TS specific input filters.  I insert the top three rules above it to

a) allow the normal TS udp port through, b) allow port 8123 to access HA and to drop all other TS traffic.

This effectively isolated the TS interface to allow only HA over port 8123 and should help protect my system.

However, This is a manual addition at this point.

```
-A INPUT -i tailscale0 -p udp -m udp --dport 41641 -j ACCEPT
-A INPUT -i tailscale0 -p tcp -m tcp --dport 8123 -j ACCEPT
-A INPUT -i tailscale0 -j DROP
-A INPUT -j ts-input
```

**Comment by tsujamin** [comment]
Sorry, didn't see this (I've fixed notifications for future Issues).

Just to be on the same page - the goal would be a method to restrict connections to your HA's Tailscale IP to just be the HA web interface/required Tailscale ports in an automated/persistent way? Also, were you adding these rules from within the add-on container, or from the host?

I can think of a couple ways this could be implemented within or external to the add-on:

  1. The addon could have a "limit access to only HA web interface" option that enables rules like yours above -  if gateways/subnet publishing were enabled though it would likely negate this option. I'd probably also need to ensure the current API/web interface port is properly detected (should be easy, since bashio does this)

  2. An option to pass in IPTables rules to the add-on.

  3. The add-on fires a HA event when it is starting up that could be consumed by an automation or add-on of your own which then applies appropriate rules (similar to https://community.home-assistant.io/t/start-an-addon-with-shell-command/27660/2) 
 
I think I like Options 1, 3 then 2 in order of preference, and option 1 seems like a sane option to add. My only concern is leaving the HA IPtables chains in an unclean state on container restart, maybe isolating them in their own chain would work though.

Curious on which of these would be workable from your perspective. It might be a week or so before I get a chance to implement it up though (although happy to take PRs 👍)

**Comment by minix1234** [comment]
Morning,

That is correct.  The idea being that one could restrict access to only the ports needed to access HA via a webpage, or through the mobile app.  

It would be a sane option from a security point of view (least privileged access, etc).  I also agree that it could get sloppy quickly.  Rules are only purged on host reboots, The add-on would need to check the existence of rules before adding them in again. (The new iptable chain is a good idea, It could be wiped and reloaded on add-on restarts)

I like the idea of option 3.  The up/down events could be very useful.

Currently, I add the rules through Portainer, while in the Tailscale add-on.  However, as the add-on has host network access the rules are added to the host's iptables (as confirmed through SSH terminal).  

That set of rules are added via the terminal manually in the following order.

```
iptables -I INPUT -i tailscale0 -j DROP
iptables -I INPUT -i tailscale0 -p tcp -m tcp --dport 8123 -j ACCEPT
iptables -I INPUT -i tailscale0 -p udp -m udp --dport 41641 -j ACCEPT
```

![image](https://user-images.githubusercontent.com/48591487/114393739-5f238700-9b68-11eb-81c5-820a93729ab7.png)

![image](https://user-images.githubusercontent.com/48591487/114395475-68adee80-9b6a-11eb-8b46-3aadc9579013.png)

**Comment by tsujamin** [comment]
Awesome thanks for clarifying - I'll try looking at this later in the week when I'm available :)

**Comment by dkvdm** [comment]
I can't get Hass to work as an exit or relay node on RPi. I'm trying to follow these docs: https://tailscale.com/kb/1104/enable-ip-forwarding/

Help would be appreciated, thank you for your hard work!

**Comment by tsujamin** [comment]
Hey @dkvdm - could you open a [new issue](https://github.com/tsujamin/hass-addons/issues/new/choose) and I'll try take a look? This issue concerns a different feature request (which I haven't gotten to yet 😢)

When you do, can you confirm you're using this Tailscale plugin (which is designed for Home Assistant), or just installing Tailscale on a regular Raspberry Pi? I only maintain this 3rd party plugin not Tailscale

**Comment by dkvdm** [comment]
> Hey @dkvdm - could you open a [new issue](https://github.com/tsujamin/hass-addons/issues/new/choose) and I'll try take a look? This issue concerns a different feature request (which I haven't gotten to yet 😢)
> 
> When you do, can you confirm you're using this Tailscale plugin (which is designed for Home Assistant), or just installing Tailscale on a regular Raspberry Pi? I only maintain this 3rd party plugin not Tailscale

I do use it as a Tailscale plugin for HASS. Ticket made here: https://github.com/tsujamin/hass-addons/issues/17
Thanks!

**Comment by minix1234** [comment]
Evening,

I have made some progress here regarding various ways to help protect home assistant while using this as a VPN.

the easiest is using the built in access control lists in Tailscale.  below is an example on restricting access to the home assistant to only port 8123.

```/// Example ACLs for restricting access to Home Assistant
{
  // Declare convenient hostname aliases to use in place of IP addresses.
  "Hosts": {
    "homeassistant": "100.88.1.86",
  },
  // Access control lists.
  "ACLs": [
    // Comment out this default match all rule
    //{ "Action": "accept", "Users": ["*"], "Ports": ["*:*"] },
   
    // user@gmail.com, can access port 8123 (Home Assistant Web)
	{ "Action": "accept", "Users": ["user@gmail.com"],"Ports": ["homeassistant:8123"] },
    { "Action": "accept", "Users": ["user@gmail.com"],"Ports": ["homeassistant:53"] },
  ]
}```json

**Comment by minix1234** [comment]
I have also implement a very crude docker image to implement my iptable changes.  call me paranoid but the ACL work on the application layer and I still want to restrict this at the socket/kernel level.

I found a neat debian project  called easywall which looks like it might lend itself as its own add-on. So I will be looking at that to hopefully get something useful and generalizable for the cummunity.

anyways I think it might be best to put this ACL info I'm the readme.  if you think that might be useful I can create a fork and send along a merge request.

let me know

**Comment by tsujamin** [comment]
Definitely happy to pull it in to the readme! Feel free to raise and I'll review/merge/close.

Thanks for your time on this

**Comment by minix1234** [comment]
no worries.  

security is important for the community
